baseurl: null
description: 'Database of Kenyan coffee trade and key actors'
exclude:
- bin
- requirements.txt
- README.md
- Gemfile*
markdown: kramdown
plugins:
- jekyll-redirect-from
timezone: Europe/Amsterdam
title: MyKahawa
url: https://archive.mykahawa.org
BASE_PATH: https://archive.mykahawa.org