baseurl: null
description: 'Database of Kenyan coffee trade and key actors'
exclude:
- bin
- requirements.txt
- README.md
- Gemfile*

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Outputting
permalink: /:categories/:title.html

# Extend functionality with plugins
plugins:
- jekyll-redirect-from
- jekyll-sitemap
timezone: Europe/Amsterdam

# Config for profile
title: MyKahawa
name: MyKahawa           # Your name
avatar: /theme/img/logo.png   # Path to an avatar image

url: https://www.mykahawa.org
BASE_PATH: https://www.mykahawa.org

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_node"]

# Wire in the SASS files in the theme directory.
sass:
  sass_dir: theme/_sass
  style: compressed

# Turn the projects into a collection.
collections:
  projects:
    output: true
    title: Projects
    permalink: /:collection/:name.html
  producers:
    output: true
    title: Producers
    permalink: /:collection/:name.html
  traders:
    output: true
    title: Traders
    permalink: /:collection/:name.html      
    
defaults:
# Turn the profile sidebar on for all pages by default, except for the
# collections, where it is off and replaced by useful things on the sidebar.
# To override this on a page, use
#    show_profile: false
# to hide the profile.
  -
    scope:
      path: ""
    values:
      show_profile: true
  -
    scope:
      path: "_posts"
    values:
      show_profile: false
      layout: defaults/post
  -
    scope:
      path: "_producers"
    values:
      show_profile: false
      layout: defaults/producer
  -
    scope:
      path: "_traders"
    values:
      show_profile: false
      layout: defaults/trader
  -
    scope:
      path: "_projects"
    values:
      show_profile: false
      layout: defaults/project
  -
    scope:
      path: "list"
    values:
      show_profile: false
      layout: defaults/list