baseurl: null
description: 'We care about coffee'
exclude:
- bin
- requirements.txt
- README.md
- Gemfile*
markdown: kramdown
plugins:
- jekyll-redirect-from
timezone: Europe/Amsterdam
title: IPBES documents
url: https://archive.mykahawa.org
